"""
Cached Experience Storage.

Redis-cached wrapper for ExperienceStorage providing automatic caching
with invalidation on writes and configurable TTL.
"""

import logging
from services.storage.experience_storage import ExperienceStorage
from services.storage.cached_storage import CachedStorage
from services.cache_config import get_ttl_for_cache_type

logger = logging.getLogger(__name__)


class CachedExperienceStorage(CachedStorage):
    """
    Cached experience storage with Redis.
    
    Wraps ExperienceStorage with automatic caching:
    - Caches get() operations (6 hours TTL - experiences change less frequently)
    - Caches query() results (15 minutes TTL)
    - Caches get_similar_experiences() results (30 minutes TTL)
    - Invalidates cache on save(), delete(), bulk operations
    """
    
    def __init__(self):
        """
        Initialize cached experience storage.
        
        Creates underlying ExperienceStorage and wraps it with caching.
        """
        storage = ExperienceStorage()
        super().__init__(
            storage=storage,
            service_name="experience",
            get_ttl=get_ttl_for_cache_type("experience"),  # 6 hours default
            query_ttl=get_ttl_for_cache_type("query_result"),  # 15 min default
            enable_query_cache=True
        )
        logger.debug("CachedExperienceStorage initialized")
        
        # Cache optimization notes:
        # - TTL values are configured in services/cache_config.py
        # - Cache keys are generated by CachedStorage base class
        # - Cache invalidation happens automatically on writes/deletes
        # - For cache warming, consider pre-loading frequently accessed experiences
    
    def store_experience(self, experience) -> str:
        """Store experience (backward compatibility)."""
        return self.save(experience)
    
    def retrieve_experience(self, experience_id: str):
        """Retrieve experience (backward compatibility)."""
        # Get from cache (via CachedStorage.get())
        data = self.get(experience_id)
        if not data:
            return None
        # Convert dict to Experience using storage's method
        return self.storage._dict_to_experience(data)
    
    def query_experiences(self, filters: dict, limit: int = 100):
        """Query experiences (backward compatibility)."""
        # Get from cache (via CachedStorage.query())
        results = self.query(filters=filters, limit=limit)
        # Convert dicts to Experience objects
        return [self.storage._dict_to_experience(r) for r in results]
    
    def get_similar_experiences(self, experience, limit: int = 10):
        """Get similar experiences (backward compatibility)."""
        return self.storage.get_similar_experiences(experience, limit)
    
    def get_experience_statistics(self, agent_name: str = None):
        """Get experience statistics (backward compatibility)."""
        return self.storage.get_experience_statistics(agent_name)

